weights: yolov5m.pt
cfg: ''
data: .\data\supermarket_dataset.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 32
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 1
project: runs/train
entity: null
name: exp13stackedNoaug_Medium
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs\train\exp13stackedNoaug_Medium
