weights: yolov5m.pt
cfg: ''
data: .\data\supermarket_dataset.yaml
hyp: data/hyp_evolve.yaml
epochs: 10
batch_size: 32
imgsz: 416
rect: false
resume: false
nosave: true
noval: true
noautoanchor: false
evolve: 100
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 1
project: runs/evolve
entity: null
name: evolution_test_Hunderd-1
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
save_dir: runs\evolve\evolution_test_Hunderd-12
