# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 450)
        Dialog.setStyleSheet("color: #ffffff; background-color: rgb(59, 62, 63);")
        self.Title = QtWidgets.QLabel(Dialog)
        self.Title.setGeometry(QtCore.QRect(0, 20, 631, 25))
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 80, 420, 500))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 135, 151, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui_elements/dulogo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 400, 631, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(250, 0, 250, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OkButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.OkButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(90, 255, 109);\n"
"font: 500 12pt \"Poppins\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Rusab/.designer/backup/startbilling.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OkButton_2.setIcon(icon)
        self.OkButton_2.setIconSize(QtCore.QSize(0, 0))
        self.OkButton_2.setObjectName("OkButton_2")
        self.horizontalLayout.addWidget(self.OkButton_2)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Title.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'poppins\'; font-size:16pt; font-weight:600; color:#ffffff;\">About</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'poppins\'; font-size:12pt;\">This is an Image recognition based billing system for supershops based on a state of the art object detection algorithm Yolov5. The application is made by -<br/><br/></span><span style=\" font-family:\'poppins\'; font-size:12pt; font-weight:600; color:#5aff6d;\">Rusab Sarmun (SH-073-045)</span></p><p align=\"justify\"><span style=\" font-family:\'poppins\'; font-size:12pt; font-weight:600; color:#5aff6d;\">Fabiha Bushra (SK-073-070)</span><span style=\" font-family:\'poppins\'; font-size:12pt;\"><br/><br/>This project has been made as the final year project of BSc in DU EEE. </span></p></body></html>"))
        self.OkButton_2.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
