# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recieptPrompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class reciept_prompt(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Prompt")
        Dialog.resize(325, 138)
        Dialog.setStyleSheet("color: #ffffff; background-color: rgb(59, 62, 63);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.yesButton = QtWidgets.QPushButton(Dialog)
        self.yesButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(90, 255, 109);\n"
"font: 500 12pt \"Poppins\";")
       
        self.yesButton.setObjectName("yesButton")
        self.gridLayout.addWidget(self.yesButton, 1, 0, 1, 1)
        self.noButton = QtWidgets.QPushButton(Dialog)
        self.noButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(90, 255, 109);\n"
"font: 500 12pt \"Poppins\";")
        
        self.noButton.setObjectName("noButton")
        self.gridLayout.addWidget(self.noButton, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Prompt"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'poppins\'; font-size:12pt;\">Do you want to generate a receipt ?</span></p></body></html>"))
        self.yesButton.setText(_translate("Dialog", "Yes"))
        self.noButton.setText(_translate("Dialog", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
